[project]
name = "slim-epoch"
authors = ["Slim Epoch Team"]
description = "Decentralized IoT Access Management Protocol"
telemetry = false
requirements = []
[contracts.epoch-access-control]
path = "contracts/epoch-access-control.clar"
depends_on = ["epoch-node-registry"]

[contracts.epoch-node-registry]
path = "contracts/epoch-node-registry.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
